### ISSUE TITLE
Wrong version of lib and pc files when UDA is installed from a tarball (EasyBuild)

### ISSUE THREAD

**Issue by olivhoenen** [ukaea/UDA#43]
In all versions of UDA installed on SDCC by @SimonPinches, the lib and associated pc file versions are set to 0.0.0 instead of being properly set as when we install UDA from a git clone. This is still the case in 2.7.5.

**Comment by stephen-dixon** [comment]
I believe this was fixed in release 2.7.6. Please could you confirm this works as expected for you now?

**Comment by SimonPinches** [comment]
I confirm this is now fixed for our installations on the SDCC cluster.
